# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/salk_toolkit',
                'doc_host': 'https://salk-ee.github.io',
                'git_url': 'https://github.com/salk-ee/salk_toolkit',
                'lib_path': 'salk_toolkit'},
  'syms': { 'salk_toolkit.io': { 'salk_toolkit.io.load_parquet_with_metadata': ('io.html#load_parquet_with_metadata', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.load_population_h5': ('io.html#load_population_h5', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.read_and_process_data': ('io.html#read_and_process_data', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.read_annotated_data': ('io.html#read_annotated_data', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.save_parquet_with_metadata': ('io.html#save_parquet_with_metadata', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.save_population_h5': ('io.html#save_population_h5', 'salk_toolkit/io.py'),
                                 'salk_toolkit.io.save_sample_h5': ('io.html#save_sample_h5', 'salk_toolkit/io.py')},
            'salk_toolkit.utils': { 'salk_toolkit.utils.batch': ('utils.html#batch', 'salk_toolkit/utils.py'),
                                    'salk_toolkit.utils.factorize_w_codes': ('utils.html#factorize_w_codes', 'salk_toolkit/utils.py'),
                                    'salk_toolkit.utils.index_encoder': ('utils.html#index_encoder', 'salk_toolkit/utils.py'),
                                    'salk_toolkit.utils.loc2iloc': ('utils.html#loc2iloc', 'salk_toolkit/utils.py'),
                                    'salk_toolkit.utils.replace_constants': ('utils.html#replace_constants', 'salk_toolkit/utils.py')}}}
