# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/salk-toolkit',
                'doc_host': 'https://salk-ee.github.io',
                'git_url': 'https://github.com/salk-ee/salk-toolkit',
                'lib_path': 'salk_toolkit'},
  'syms': {'salk_toolkit.core': {'salk_toolkit.core.foo': ('core.html#foo', 'salk_toolkit/core.py')}}}
